//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_A_Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarInfo()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public string CarNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public string TexPassport { get; set; }
        public Nullable<decimal> DailyPrice { get; set; }
        public Nullable<int> CarModelId { get; set; }
        public Nullable<int> ColorId { get; set; }
    
        public virtual CarColor CarColor { get; set; }
        public virtual CarModel CarModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
