//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_A_Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CarInfoId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> OverDate { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> LateTime { get; set; }
        public Nullable<decimal> SumPrice { get; set; }
        public Nullable<decimal> LatePrice { get; set; }
    
        public virtual CarInfo CarInfo { get; set; }
        public virtual ClientInfo ClientInfo { get; set; }
    }
}
